version: '3'

services:
    web:
        build: .
        ports:
          - '8000:8000'
        environment:
          - REDIS_HOST=cache
          - REDIS_PORT=6379
          - REDIS_DB=0
        depends_on:
          - cache
    cache:
        image: redis
        ports:
          - '6380:6379'

